### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by lulis** [mapbox/leaflet-omnivore#42]
Hi,
On CHANGELOG omnivore seems to support IE9. But if you try to open any of the Mapbox Omnivore samples (like https://www.mapbox.com/mapbox.js/example/v1.0.0/omnivore-kml/) on IE9, page will hang an browser will say that "mapbox.com is not responding".

Trying on home, i got the message "No such interface supported" on JS console. Char 29 on this line:
https://github.com/mapbox/leaflet-omnivore/blob/v0.3.0/leaflet-omnivore.js#L786

I'm testing on the IE 9/Win 7 virtualbox image from modern.IE 
Hope that you can fix it, there is a lot of people still using IE9...

Thanks.

**Comment by tmcw** [comment]
Closing; happy to accept a pull request implementing this change, otherwise IE9 is not a high maintainer concern.
