### ISSUE TITLE
Pass options to generated GeoJson

### ISSUE THREAD

**Issue by dmolineus** [mapbox/leaflet-omnivore#54]
Thanks for sharing the great omnivore plugin. One thing i really miss is that you do not provide a way to pass options to the generated geojson object.

I know you provide the `ready` event but for some cases it does not work. For instance I want to generate a CircleMarker for a given point. Usually the GeoJSON layer turns the point into a marker, with the `pointToLayer` callback I can change this.

So it would be really helpful if you allow to pass the `pointToLayer`, `style`, `onEachFeature`, `filter` and `coordsToLatLng` to the geojson layer.

I know by creating a custom layer before and pass it, also works...

Any reasons not to add this feature?

**Comment by tmcw** [comment]
I don't totally follow:

> One thing i really miss is that you do not provide a way to pass options to the generated geojson object.

and

> I know by creating a custom layer before and pass it, also works...

By creating a custom layer and passing options to it, there is a way to provide options to the generated geojson object. How is this not clear, especially when you state it here and it's [thoroughly documented as the first example in the readme?](https://github.com/mapbox/leaflet-omnivore#custom-layers)

**Comment by dmolineus** [comment]
Sorry, I've read the documentation, but simply missed the way to solve it. During writing this issue I've understood how to do it.

Nevermind, gonna close it.
