### ISSUE TITLE
Crossing dateline with Omnivore

### ISSUE THREAD

**Issue by ilblog** [mapbox/leaflet-omnivore#58]
This issue goes maybe down to Leaflet polygon behaviour. Any track crossing dateline draws a line through whole world.

![screen shot 2015-06-05 at 10 21 13](https://cloud.githubusercontent.com/assets/7228326/8002192/1adbfd34-0b6d-11e5-807f-3d8ed64b0178.png)

**Comment by k-nut** [comment]
I guess this is closely related to issue #47 Since they both break at the same level.We solved a similar issue here https://github.com/johnjohndoe/CodeForFreedom2014/issues/2 . Maybe this helps for your use case as well?

**Comment by tmcw** [comment]
The solution to this issue is to create a line with coordinates > 180 or < -180, so that they follow across the dateline. Otherwise it is not possible for this or any library to unambiguously decide whether a line crosses the dateline or goes across the earth.
