### ISSUE TITLE
Custom marker icon on csv?

### ISSUE THREAD

**Issue by dels07** [mapbox/leaflet-omnivore#67]
Is there any way to specify custom marker as defined in csv?
The feature already available in:
https://github.com/joker-x/Leaflet.geoCSV
http://joker-x.github.io/Leaflet.geoCSV/example/icons/index.html

**Comment by tmcw** [comment]
Nope, as [documented](https://github.com/mapbox/leaflet-omnivore#custom-layers), custom layers are possible but aren't specific to any file format.
