### ISSUE TITLE
mapbox + ionic issue

### ISSUE THREAD

**Issue by yoohoogun114** [mapbox/leaflet-omnivore#68]
my controller code here
    var add_omnivore = omnivore.csv('/lib/airports3.csv').addTo(map);
It works fine in my web browser ( ionic serve)
but It is not working on my IOS simulator

Error Message here
publicFacility_prj[21547:1281476] error JSON.stringify()ing argument: TypeError: JSON.stringify cannot serialize cyclic structures.

**Comment by tmcw** [comment]
Closing; it looks like there's a library that's inserting itself in converted results.
