### ISSUE TITLE
Uncaught TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by jimmyangel** [mapbox/leaflet-omnivore#69]
Hi,

I am seeing this error with the attached GPX file. It is probably an invalid GPX file, but I would expect to get the 'error' callback instead of an exception.

Uncaught TypeError: Cannot read property 'line' of undefined - leaflet-omnivore.js:1019

To get around this for now I am setting up a global window.onerror handler, but that is not ideal.

Thank you

[AAAgpsbabel_output.txt](https://github.com/mapbox/leaflet-omnivore/files/61924/AAAgpsbabel_output.txt)

**Comment by tmcw** [comment]
Thanks for the bug report! This is fixed with the upgrade of toGeoJSON, which brings in the upstream fix https://github.com/mapbox/togeojson/commit/bfec7246d0863cde5a180488d771776f9e292ced
