### ISSUE TITLE
Support for AngularJS?

### ISSUE THREAD

**Issue by rblades** [mapbox/leaflet-omnivore#70]
Trying to convert html site to single page web app using Angular. I have consulted [the Angular leaflet docs](https://angular-ui.github.io/ui-leaflet/#!/). Yet I am getting nothing when trying to preview the map. Trying to pull from CSV. Angular ui-leaflet docs show nothing about CSV, just geojson.

This was the original script for the html map:

` var map = L.map('map', {
    center: [45.8256661,-77.1182135],
    zoom: 13,
    layers:[
      L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}.png'),
      L.tileLayer('http://warp.woritldmap.harvard.edu/maps/tile/4322/{z}/{x}/{y}.png')
    ]
});

            //enter path for .csv here
            omnivore.csv('sites/aa-sites-popup.csv')
             .on('ready', function(layer) {

        this.eachLayer(function(marker) {

            // Bind a popup to each icon based on the same properties
            // Adds coloumns of extra info to marker popup
            marker.bindPopup(marker.toGeoJSON().properties.timePeriod +
                marker.toGeoJSON().properties.siteName + '<br><br> ' +
                marker.toGeoJSON().properties.info + '<br><br> ' +
                marker.toGeoJSON().properties.link, {autoPanPadding: [5,55]});
        });
    })
            .addTo(map); `

Cheers

**Comment by tmcw** [comment]
@rblades this is a Leaflet plugin, so the formats it supports will not be in the documentation for Leaflet-Angular, which is a wrapper around only core Leaflet, not any plugins. Acquiring a reference to the underlying Leaflet Map object is [documented in the documentation for the angular wrapper](https://github.com/angular-ui/ui-leaflet#how-to-use-it).
