### ISSUE TITLE
Installation URL still uses 0.2.0 

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/leaflet-omnivore#72]
The URL in the readme has a ver number of 0.2.0 and what is likely much older code of leaflet-omnivore. 

The contents of the install url differ [(filediff)](https://www.diffchecker.com/udhvhb0t) (in the filediff, left is the URL listed in the readme, and the right is what's in master as of https://github.com/mapbox/leaflet-omnivore/blob/abae5bd859d5c9702a0eef9666faac3d0ff3c0f7/leaflet-omnivore.min.js

**Comment by skorasaurus** [comment]
I had thought to make a pull request and update the URL to https://api.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.3.1/leaflet-omnivore.min.js (which matches the syntax of other mapbox.js plugins) but its contents are close but not exact with https://github.com/mapbox/leaflet-omnivore/blob/abae5bd859d5c9702a0eef9666faac3d0ff3c0f7/leaflet-omnivore.min.js

**Comment by tmcw** [comment]
:+1: 0.3.1 is the correct version, making the change now.

**Comment by tmcw** [comment]
Fixed in c546519ec6715b8aa3fed4740890699cad549881
