### ISSUE TITLE
Rename leaflet-omnivore to omnivore

### ISSUE THREAD

**Issue by tristen** [mapbox/leaflet-omnivore#73]
Unless I'm missing something - there's no dependency relationship to Leaflet?

ref https://github.com/mapbox/mapbox-gl-js/issues/1170

**Comment by tristen** [comment]
Related - right now we host a CDN link of the lib from 

```
https://api.mapbox.com/mapbox.js/plugins/leaflet-omnivore/v0.2.0/leaflet-omnivore.min.js
```

I wonder if this should be from a more generalized path like 

```
https://api.mapbox.com/plugins/omnivore/v0.2.0/omnivore.min.js
```

**Comment by tmcw** [comment]
This is a Leaflet plugin: it is [dependent on Leaflet](https://github.com/mapbox/leaflet-omnivore/blob/master/index.js#L60).
