### ISSUE TITLE
Gpx layer with single markers (in group)

### ISSUE THREAD

**Issue by tecnocoma75** [mapbox/leaflet-omnivore#74]
Hi,

i'm trying to load gps points from a gpx file . Omnivore is ok, but i can only show the path (polyline), not the group of markers (i mean point contained in gpx file that are the base for the path). I'd like to let the user choose between 2 layer, the one with the markers, and the other one with the path. This is useful because in a gps web app, user can click on markers and get specific information (date,gps coord,) on popup. This would be kind to do with Omnivore, also because i've already done my app (thanx to omnivore.gpx) that show an animated icone along the path...but can't show the layer of the single points overlappen to the path. Thanx a lot in advance

**Comment by tmcw** [comment]
Thanks for the suggestion! I'd be happy to accept a pull request to [toGeoJSON, the library that does GPX decoding for leaflet-omnivore](https://github.com/mapbox/togeojson). Here's the part that does the GPX decoding: https://github.com/mapbox/togeojson/blob/master/togeojson.js#L288
