### ISSUE TITLE
Can't load GPX on iOS 9+

### ISSUE THREAD

**Issue by USSliberty** [mapbox/leaflet-omnivore#76]
Hi all,

don't know if it's the right place for this problem, but i will try anyway. 
I have an issue loading a GPX file only on **iOS9** (on iOS8 and android all work correctly). 

I see on the inspector that the ajax request it's ok, but on the map nothing happens. No errors, nothing. Simply seems like the response is ignored somewhere in the code.

After some debugging if found the problem, and is located inside the "onload" function of "gpxLoad". (See screenshot)

![schermata 2016-03-08 alle 14 41 53](https://cloud.githubusercontent.com/assets/829586/13603265/326d778a-e53c-11e5-8659-23212d6b9322.png)

Anyone have experienced the same problem?
```javascript
function gpxLoad(url, options, customLayer) {
   var layer = customLayer || L.geoJson();
    xhr(url, onload);
    function onload(err, response) {
        // ---------
        // 'response' is null, 'err' is not null but it contains the response object!
        // ---------
        var error;
        if (err) return layer.fire('error', { error: err });
        function avoidReady() {
            error = true;
        }
        layer.on('error', avoidReady);
        gpxParse(response.responseXML || response.responseText, options, layer);
        layer.off('error', avoidReady);
        if (!error) layer.fire('ready');
    }
    return layer;
} ```

**Comment by svzi** [comment]
I'm having exactly the same issue, only for KML files.

I have modified the corresponding function from:
`function kmlLoad(url, options, customLayer) {
    var layer = customLayer || L.geoJson();
    xhr(url, onload);
    function onload(err, response) {
        var error;
        if (err) return layer.fire('error', { error: err });
        function avoidReady() {
            error = true;
        }
        layer.on('error', avoidReady);
        kmlParse(response.responseXML || response.responseText, options, layer);
        layer.off('error', avoidReady);
        if (!error) layer.fire('ready');
    }
    return layer;
}
`
To:
`function kmlLoad(url, options, customLayer) {
    var layer = customLayer || L.geoJson();
    xhr(url, onload);
    function onload(err, response) {
        var error;
        // modified code - start
        if (err && !err.responseText) return layer.fire('error', { error: err });
        if (err.responseText) {
            response = err;
        }
        // modified code - end
        function avoidReady() {
            error = true;
        }
        layer.on('error', avoidReady);
        kmlParse(response.responseXML || response.responseText, options, layer);
        layer.off('error', avoidReady);
        if (!error) layer.fire('ready');
    }
    return layer;
}
`

Just a workaround and probably not the best solution, but at least it's useable again. If someone has an idea on how to improve that further, please let me know.

**Comment by tmcw** [comment]
I'm going to guess you're loading from the filesystem and the GPX file doesn't come with a header indicating that it's XML, so XMLHttpRequest isn't interpreting it as such?

**Comment by svzi** [comment]
Despite being not the thread starter your assumption is right, at least for my issue regarding the KML file.

**Comment by tmcw** [comment]
Cool, so the solution is [the one noted in the toGeoJSON readme](https://github.com/mapbox/togeojson#protips) - you can use DOMParser's parseFromString method to convert a string to an XML DOM.

**Comment by svzi** [comment]
Should that work for KML as well? I'm sure all other methods, loading stuff from local filesystem, are affected as well.
