### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by kennynaoh** [mapbox/leaflet-omnivore#79]
What kind of BSD do you use?
Thanks

https://github.com/cdnjs/cdnjs/pull/7754
https://github.com/cdnjs/cdnjs/issues/6746

**Comment by kennynaoh** [comment]
Hello @tmcw ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs).
We want to host your library.
But there is a license problem.
Maybe you could take a look at this.
[license](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json)
Thanks.

**Comment by tmcw** [comment]
As in https://github.com/mapbox/leaflet-omnivore/blob/master/LICENSE - BSD 3 Clause.

**Comment by kennynaoh** [comment]
Thanks.
