### ISSUE TITLE
GeoJSon doesnt show

### ISSUE THREAD

**Issue by rajanski** [mapbox/leaflet-omnivore#83]
Hi I got the following simple lines in my map (CORS restrictions are switched off in Chrome):

```
omnivore.geojson("stops.geojson").addTo(map);
```

But the markers do not show up.

If I add the markers as in

```
$.getJSON("stops.geojson",function(data){
    // add GeoJSON layer to the map once the file is loaded
    L.geoJson(data).addTo(map);
  });
```

they show up.

This is the Geojson data:
`{"type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [39.2796017, -6.8224933]}, "type": "Feature", "properties": {"previous_dominating_activity": "still", "bearing": 0, "route": null, "previous_dominating_activity_confidence": 60, "current_dominating_activity": "in_vehicle", "current_dominating_activity_confidence": 77, "timestamp": "2015-11-11T09:03:01+0300", "created_at": "2015-11-11 06:03:12", "feature": "passive_tracking", "id": 4, "speed": 0, "altitude": 0.0, "accuracy": 23.0}}]}`

**Comment by BergWerkGIS** [comment]
This GeoJSON is not valid:
```
"route": null, <"previous_dominating_activity_confidence": 60
               ^
```

**Comment by rajanski** [comment]
i know. this had slipped in. Anyway it still doesnt work

**Comment by rajanski** [comment]
Ok i did some more testing.
It works if I load the file from the web as in:

`omnivore.geojson('https://raw.githubusercontent.com/rajanski/d2d_cc/master/stops_short.geojson').addTo(map);`

but it doesnt work if I load  a local file

`omnivore.geojson("stops.geojson").addTo(map);`

**Comment by tmcw** [comment]
Sorry, we're unable to debug problems that aren't reproducible on a website: local file access is not part of leaflet-geojson's scope. Running websites locally - with file access and not with a local server - breaks any guarantees of any libraries working. I'd recommend using a local webserver like [python's](https://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python).
