### ISSUE TITLE
zoomDelta not working

### ISSUE THREAD

**Issue by codeplan** [mapbox/leaflet-omnivore#87]
zoomDelta is not working with leaflet-omnivore.js 0.3.2v. I am using it as following:
var map = L.map('map', {minZoom: 4, zoomDelta:0.5, attributionControl:false} ).

I checked it using map.getZoom() after clicking on default zoomcontrols buttons '+' and '-'. The difference it is shows is 1 after the click.

**Comment by tmcw** [comment]
leaflet-omnivore adds data to Leaflet. It uses stock Leaflet layers inside, and only uses default types of Leaflet. If you're running into any problem related to interactivity of the map after the data is loaded, that problem is Leaflet's, not leaflet-omnivore's.
