### ISSUE TITLE
call setGeoJSON before addData

### ISSUE THREAD

**Issue by bhaskarvk** [mapbox/leaflet-omnivore#90]
Currently addData is called first after which setGeoJSON is called on the layer.

By default L.geojson has no method called 'setGeoJSON', but If I want to use a custom layer, it would be better if setGeoJSON is called before addData.
This allows for the geoJSON to be pre processed before addData is called, allowing for us to set feature styles etc, so that when addData is called and layers are added styles are ready.

**Comment by tmcw** [comment]
Thanks for this report - I agree that the current behavior is problematic, but it seems like this shouldn't be an ordering relationship: the method should instead use `else if` to ensure only one of addData or setGeoJSON is called.

**Comment by bhaskarvk** [comment]
Yes that would work too, I can always call addData from my setGeoJSON. Thanks much!
