### ISSUE TITLE
Broken bower install

### ISSUE THREAD

**Issue by jalandis** [mapbox/leaflet-omnivore#97]
Missing files when installing version 0.3.4 with bower.

* bower_components/leaflet-omnivore/leaflet-omnivore.js 
* bower_components/leaflet-omnivore/leaflet-omnivore.min.js

There is also a mismatch in versions with the components.js file

```
bower leaflet-omnivore#0.3.4         mismatch Version declared in the json (0.2.0) is different than the resolved one (0.3.4)
```

Reverting to version 0.3.2 works.

**Comment by tmcw** [comment]
Bower is no longer supported: please use `npm` or the CDN.
